In [9]:
import numpy as np
import matplotlib.pyplot as plt #importamos las librerias correspondientes
import math
##insertamos la matriz 
A=np.array([[7,1,-1,2],
            [1,8,0,-2],
            [-1,0,4,-1],
            [2,-2,-1,6]])
b=np.array([3,-5,4,-3])
k=8  ##Numero de iteracione spara llegar al valor [ 1. -1.  1. -1.]
n=A.shape[1]
D=np.eye(n) # MATRIZ DE LA IDENTIDAD
D[np.arange(n),np.arange(n)]=A[np.arange(n),np.arange(n)] 
LU=D-A
##Matriz triagonal superiro e inferior 
L=np.tril(LU)
U=np.triu(LU)
DL=D-L
##Almacenamiento de vectores
X=np.zeros(n)
print(" ",0,"Vector Inicial:",X)
print(A)
print("\t\t\tMetodo Gaus Seidel")
for i in range(k):
    DL_inv=np.linalg.inv(DL)
    X=np.dot(np.dot(DL_inv,U),X)+np.dot(DL_inv,b)
    print("La interaccion",i+1,"",X.round(decimals=4))
print(" ")
##Error cometido en la solucion [ 1. -1.  1. -1.]
print("\x1b[1;34m"+"ERROR: ")
xR = ([1, -1, 1, -1])
e = np.zeros(4)
for i in range(4):
    e[i] = (xR[i] - X[i]) / xR[i]
    print('x',i+1, 'es =', 100 * abs(e[i]), '%')

  0 Vector Inicial: [0. 0. 0. 0.]
[[ 7  1 -1  2]
 [ 1  8  0 -2]
 [-1  0  4 -1]
 [ 2 -2 -1  6]]
			Metodo Gaus Seidel
La interaccion 1  [ 0.4286 -0.6786  1.1071 -0.6845]
La interaccion 2  [ 0.8793 -0.906   1.0487 -0.9203]
La interaccion 3  [ 0.9708 -0.9764  1.0126 -0.9803]
La interaccion 4  [ 0.9928 -0.9942  1.0031 -0.9951]
La interaccion 5  [ 0.9982 -0.9986  1.0008 -0.9988]
La interaccion 6  [ 0.9996 -0.9996  1.0002 -0.9997]
La interaccion 7  [ 0.9999 -0.9999  1.     -0.9999]
La interaccion 8  [ 1. -1.  1. -1.]
 
ERROR: 
x 1 es = 0.0026632163637962947 %
x 2 es = 0.002157104000244381 %
x 3 es = 0.0011583978638318726 %
x 4 es = 0.001799839765326272 %
