In [14]:
import numpy as np
import matplotlib.pyplot as plt #importamos la libreria matplotlic para la definicon de las funciones
import math 
## SISTEMA MATRICIAL Y TERMINOS INTEPENDIENTES
A=np.array([[6,0,0,0],
            [3,6,0,0],
            [4,-2,7,0],
            [5,-3,9,21]])
B=np.array([12,
            -12,
            14,
            -2])
# VECTOR DE ALMACENAMIENTO
n=np.size(B)
x=np.zeros(n)

# Metodo de sustitucion progresiva Sustitución progresiva
for i in range (n):
    sumj=0
    for j in range (i):
        sumj+=A[i,j]*x[j]
    x[i]=(B[i]-sumj)*1/A[i,i]

print ("\tMatriz")
print(A,B)##imprimimos matriz
print ("\x1b[1;34m"+"\tMatriz sustitucion progresiva")
print(x) ##imprime la respuesta


	Matriz
[[ 6  0  0  0]
 [ 3  6  0  0]
 [ 4 -2  7  0]
 [ 5 -3  9 21]] [ 12 -12  14  -2]
	Matriz sustitucion progresiva
[ 2. -3.  0. -1.]
