In [19]:
import numpy as np
import matplotlib.pyplot as plt #importamos las librerias correspondientes
import math
##Ingreso de matriz
A=np.array([[7,1,-1,2], [1,8,0,-2],[-1,0,4,-1],[2,-2,-1,6]])
B=np.array([3,-5,4,-3])
print("La matriz ingresada es:")
print(A)
print("\n",B)
j=15 ##Numero de iteracione spara llegar al valor [ 1. -1.  1. -1.]
n=A.shape[1] 
D=np.eye(n) 
D[np.arange(n),np.arange(n)]=A[np.arange(n),np.arange(n)]
LU=D-A
##Matriz triagonal superiro e inferior 
L=np.tril(LU) 
U=np.triu(LU)
##Almacenamiento de vectores
X=np.zeros(n) 
E=[]
print("\t\t\tMetodo Jacobi")
print("Iteración",0,"es:",X)
#Metodo Jacobi
for i in range(j):
    D_inv=np.linalg.inv(D)
    X=np.dot(np.dot(D_inv,L+U),X)+np.dot(D_inv,b)
    
    print("Iteración",i+1, "es:",X.round(decimals=4))
print("\x1b[1;34m"+"ITERACIONES")
print("CONTIENE", i+1, "Iteraciones")
##Error cometido en la solucion [ 1. -1.  1. -1.]
print("\x1b[1;34m"+"ERROR: ")
xR = ([1, -1, 1, -1])
e = np.zeros(4)
for i in range(4):
    e[i] = (xR[i] - X[i]) / xR[i]
    print('x',i+1, 'es =', 100 * abs(e[i]), '%')

La matriz ingresada es:
[[ 7  1 -1  2]
 [ 1  8  0 -2]
 [-1  0  4 -1]
 [ 2 -2 -1  6]]

 [ 3 -5  4 -3]
			Metodo Jacobi
Iteración 0 es: [0. 0. 0. 0.]
Iteración 1 es: [ 0.4286 -0.625   1.     -0.5   ]
Iteración 2 es: [ 0.8036 -0.8036  0.9821 -0.6845]
Iteración 3 es: [ 0.8793 -0.8966  1.0298 -0.872 ]
Iteración 4 es: [ 0.9529 -0.9529  1.0018 -0.9203]
Iteración 5 es: [ 0.9708 -0.9742  1.0081 -0.9683]
Iteración 6 es: [ 0.9884 -0.9884  1.0006 -0.9803]
Iteración 7 es: [ 0.9928 -0.9936  1.002  -0.9922]
Iteración 8 es: [ 0.9971 -0.9971  1.0002 -0.9951]
Iteración 9 es: [ 0.9982 -0.9984  1.0005 -0.9981]
Iteración 10 es: [ 0.9993 -0.9993  1.     -0.9988]
Iteración 11 es: [ 0.9996 -0.9996  1.0001 -0.9995]
Iteración 12 es: [ 0.9998 -0.9998  1.     -0.9997]
Iteración 13 es: [ 0.9999 -0.9999  1.     -0.9999]
Iteración 14 es: [ 1.     -1.      1.     -0.9999]
Iteración 15 es: [ 1. -1.  1. -1.]
ITERACIONES
CONTIENE 15 Iteraciones
ERROR: 
x 1 es = 0.0026632163637962947 %
x 2 es = 0.0023597059060964654 %
x 