In [18]:
# Descomposición de Cholesky

from numpy import array
from numpy.linalg import cholesky
# Definiendo una matriz simétrica
A = array([
    [4, 6, 10],
    [6, 25, 19],
    [10, 19, 62]
])
print(A)
# Factorización
L = cholesky(A)
print(L)
# Reconstruyendo
B = L.dot(L.T)
print(B)


[[ 4  6 10]
 [ 6 25 19]
 [10 19 62]]
[[2. 0. 0.]
 [3. 4. 0.]
 [5. 1. 6.]]
[[ 4.  6. 10.]
 [ 6. 25. 19.]
 [10. 19. 62.]]


In [40]:
def isSymetric(A):
    return np.array_equal(A, A.T)

def isPosDef(A):
    val, vec = np.linalg.eig(A)
    return all(i>0 for i in val)


In [41]:
a = np.array([[5,4],[4,5]])

In [42]:
def cholesky(B, b):
    #Comprobamos que sea simetrica y positiva definida:
    if isSymetric(A) and isPosDef(A):
        R = np.linalg.cholesky(A)
        RT = R.T

        c = solve_triangular(R, b, lower=True)#Especificamos que es la tringular inferior
        
        x = solve_triangular(R, c)#Solve triangular ocupa la diagonal superior por defecto
        return x
    else:
        return "NO SE PUEDE APLICAR CHOLESKY"

In [43]:
cholesky(np.diag(np.array([1,2,3])), np.array([1,2,3]))

'NO SE PUEDE APLICAR CHOLESKY'

In [44]:
B = np.array([[4, 6, 10], [6, 3, 19], [10, 19, 62]])
cholesky(A, np.zeros(3))

'NO SE PUEDE APLICAR CHOLESKY'