In [12]:
import numpy as np
import matplotlib.pyplot as plt #importamos las librerias correspondientes
import math
##Ingreso de matriz
A = np.array([[7, 1, -1, 2], 
              [1, 8, 0, -2], 
              [-1, 0, 4, -1], 
             [2, -2, -1, 6]])
b = np.array([3, -5, 4, -3])
k = 5 ##Numero de iteracione spara llegar al valor [ 1. -1.  1. -1.]
w = 1.1
n = A.shape[1]
D = np.eye(n)  
D[np.arange(n), np.arange(n)] = A[np.arange(n), np.arange(n)]  
LU = D - A
##Matriz triagonal superiro e inferior 
L = np.tril(LU)
U = np.triu(LU)
##Almacenamiento de vectores
D_wL = D - w * L
X = np.zeros(n)
print(" ", 0, "Vector Inicial:", X)
print(A)
print("\t\t\tMetodo SOR")
for i in range(k):
    D_wL_inv = np.linalg.inv(D_wL)
    X = np.dot(np.dot(D_wL_inv, (1 - w) * D + w * U), X) + w * np.dot(D_wL_inv, b)
    print("la interaccion" ,i+1, "obtenida es:", X.round(decimals=4))

print(" ")
##Error cometido en la solucion [ 1. -1.  1. -1.]
print("\x1b[1;34m"+"ERROR: ")
xR = ([1, -1, 1, -1])
e = np.zeros(4)
for i in range(4):
    e[i] = (xR[i] - X[i]) / xR[i]
    print('x',i+1, 'es =', 100 * abs(e[i]), '%')

  0 Vector Inicial: [0. 0. 0. 0.]
[[ 7  1 -1  2]
 [ 1  8  0 -2]
 [-1  0  4 -1]
 [ 2 -2 -1  6]]
			Metodo SOR
la interaccion 1 obtenida es: [ 0.4714 -0.7523  1.2296 -0.7733]
la interaccion 2 obtenida es: [ 0.9788 -0.9595  1.0335 -0.9939]
la interaccion 3 obtenida es: [ 0.9991 -1.0022  0.9981 -1.0015]
la interaccion 4 obtenida es: [ 1.0006 -1.0003  1.     -1.0002]
la interaccion 5 obtenida es: [ 1. -1.  1. -1.]
 
ERROR: 
x 1 es = 0.0029419032669952827 %
x 2 es = 0.002681983306263014 %
x 3 es = 0.0036134375151153364 %
x 4 es = 0.0009534752473339125 %
